routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function () {
    Route::get('/', function () {
        return view('auth.login');
    });
    
    Route::resource('articles','App\Http\Controllers\ArticleController');

    Route::resource('todoLists','App\Http\Controllers\TodoListController');

    Route::post('/todoLists/update/{item_id}', 'App\Http\Controllers\TodoListController@update');
    Route::post('/removeStockV/{med_id}/{est_id}', 'establecimientos_has_ventasController@removeStockV');

    // Route::get('/todoLists/{id}', 'App\Http\Controllers\TodolistController@index')->name('todoList.index');

    Route::get('/dash','App\Http\Controllers\ArticleController@index')->name('dash');

    // Route::middleware(['auth:sanctum', 'verified'])->get('/dash', function () {
    //     return view('dash.index');
    // })->name('dash');

});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Article;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::all()->where('user_id',Auth::user()->id);
    
        return view('article.index')->with('articles',$articles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('article.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $article = new Article();

        $article->name_list = $request->name_list;
        $article->user_id = Auth::user()->id;
        $article->save();

        return redirect('articles');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        return view('article.edit')->with('article',$article);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $article = Article::find($id);

        $article->name_list = $request->name_list;
        $article->user_id = Auth::user()->id;
        $article->save();

        return redirect('articles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::find($id);
        $article->delete();

        return redirect('articles');
    }
}

resources/views/article/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Create a new to-do list</h1>
    <hr>
@stop

@section('content')

<form action="/articles" method="post" enctype="multipart/form-data">
    @csrf
    <div class="mb-3">
        <label for="name_list" class="form-label">To-do list name</label>
        <input id="name_list" type="text" name="name_list" class="form-control" placeholder="Name" tabindex="1">
    </div>
    <a href="/articles" class="btn btn-secondary" tabindex="3"><i class="fa fa-arrow-left"></i> Cancel</a>
    <button type="submit" id="sub" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
</form>
@endsection

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script type="text/javascript">
    $("#sub").click(function(e) {
            var name_list = document.getElementById('name_list').value;
            var description = document.getElementById('description').value;
            if (name_list.trim() == '') {
                $('#name_list').addClass('is-invalid').focus();
                Swal.fire({
                    icon: 'warning',
                    title: 'The name of the list is required'
                });
                return false;
            } else {
                $('#name_list').removeClass('is-invalid');
            }
    });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
@stop

resources/views/article/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Edit the item selected</h1>
@stop

@section('content')

<form action="/articles/{{$article->id}}" method="post">
    @csrf
    @method('PUT')
    <div class="mb-3">
        <label for="name_list" class="form-label">To-do list name</label>
        <input id="name_list" type="text" name="name_list" class="form-control" placeholder="Name" tabindex="1" value="{{$article->name_list}}">
    </div>
    <a href="/articles" class="btn btn-secondary" tabindex="3"><i class="fa fa-arrow-left"></i> Cancel</a>
    <button type="submit" id="sub" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
</form>
@endsection

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script type="text/javascript">
    $("#sub").click(function(e) {
            var name_list = document.getElementById('name_list').value;
            var description = document.getElementById('description').value;
            if (name_list.trim() == '') {
                $('#name_list').addClass('is-invalid').focus();
                Swal.fire({
                    icon: 'warning',
                    title: 'The name of the list is required'
                });
                return false;
            } else {
                $('#name_list').removeClass('is-invalid');
            }
    });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    
@stop

resources/views/article/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Home</h1>
    <h3>To-do list</h3>
    <hr>
@stop

@section('content')
<table class="table table-bordered table mt-4">
    <thead>
        <th scope="col">ID</th>
        <th scope="col">To-do list</th>
        <th scope="col">Action</th>
    </thead>
    <tbody>
        @foreach ($articles as $article)
            <tr>
                <td style="width:25%;clear:both">{{$article->id}}</td>
                <td style="width:25%;clear:both">{{$article->name_list}}</td>
                <td style="width:25%;clear:both">
                    <form action="{{ route('articles.destroy', $article->id) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <a href="/articles/{{$article->id}}/edit"><button type="button" title="Edit to-do list" class="btn btn-outline-warning btn-circle"><i class="fa fa-pencil-alt" aria-hidden="true"></i> </button></a>
                        {{-- <a href="{{ route('todoLists.index',$article->id) }}"><button type="button" title="To-do list" class="btn btn-outline-info btn-circle"><i class="fas fa-eye" aria-hidden="true"></i> </button></a> --}}
                        <a href="/todoLists/?id={{$article->id}}"><button type="button" title="To-do list" class="btn btn-outline-info btn-circle"><i class="fas fa-eye" aria-hidden="true"></i> </button></a>
                        <button type="submit" class="btn btn-danger" hidden id="btnDelete{{$article->id}}">Delete</button>
                        <button type="button" onclick="del({{$article->id}})" data-toggle="modal" data-target="#modal-delete-med-{{$article->id}}" title="Delete to-do list" class="btn btn-outline-danger btn-circle"><i class="fa fa-trash"></i></button>
                    </form>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>
@endsection

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script type="text/javascript">
    function del(id){
         const swalWithBootstrapButtons = Swal.mixin({
              customClass: {
                confirmButton: 'btn btn-outline-success m-3',
                cancelButton: 'btn btn-outline-danger m-3'
              },
              buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
              title: '¿Are you sure you want to delete this?',
              // text: "You won't be able to revert this!",
              icon: 'question',
              showCancelButton: true,
              confirmButtonText: 'Yes',
              cancelButtonText: 'Cancel',
              reverseButtons: true,
              // width: '850px'
            })
            .then((result) => {
              if (result.isConfirmed){
                $('#btnDelete'+id).click();
              }
            })
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
@stop