routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth')->group(function () {
    Route::get('/', function () {
        return view('auth.login');
    });
    
    Route::resource('articles','App\Http\Controllers\ArticleController');

    Route::resource('todoLists','App\Http\Controllers\TodoListController');

    Route::post('/todoLists/update/{item_id}', 'App\Http\Controllers\TodoListController@update');
    Route::post('/removeStockV/{med_id}/{est_id}', 'establecimientos_has_ventasController@removeStockV');

    // Route::get('/todoLists/{id}', 'App\Http\Controllers\TodolistController@index')->name('todoList.index');

    Route::get('/dash','App\Http\Controllers\ArticleController@index')->name('dash');

    // Route::middleware(['auth:sanctum', 'verified'])->get('/dash', function () {
    //     return view('dash.index');
    // })->name('dash');

});

app/Models/TodoList.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TodoList extends Model
{
    use HasFactory;
}

app/Http/Controllers/TodoListController.php
<?php

namespace App\Http\Controllers;
use App\Models\TodoList;
use App\Models\Article;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use DataTables;

class TodoListController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $article = Article::find($request->id);
        $articles = Article::all()->where('user_id',Auth::user()->id);
        
        if($article != null){
            $todoLists = TodoList::all()->where('user_id',Auth::user()->id)->where('list_id', $request->id);
            if($article->user_id == Auth::user()->id){
                return view('todoList.index')->with('article', $article)->with('todoLists',$todoLists);
            } else {
                return view('article.index')->with('articles',$articles);
            }
        } else{
            return view('article.index')->with('articles',$articles);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $todoList = new TodoList();

        $todoList->name_item = $request->item_todo;
        $todoList->list_id = $request->list_id;
        $todoList->user_id = Auth::user()->id;
        $todoList->status = 0;
        $todoList->save();

        $article = Article::find($request->list_id);
        $todoLists = TodoList::all()->where('user_id',Auth::user()->id)->where('list_id', $request->list_id);
        
        return redirect("/todoLists/?id=".$request->list_id)->with('article', $article)->with('todoLists',$todoLists);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id)
    {
        $todoList = TodoList::find($id);
        if($todoList->status == 0){
            $todoList->status = 1;
            $todoList->save();
        }else{
            $todoList->status = 0;
            $todoList->save();
        }

        // return response()->json(['var' => ''.$newStatus.'']);
        return Response()->json(["response" => 1], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $todoList = TodoList::find($id);
        $list_id = $todoList->list_id;
        $todoList->delete();
        $article = Article::find($list_id);
        $todoLists = TodoList::all()->where('user_id',Auth::user()->id)->where('list_id', $list_id);
        
        return redirect("/todoLists/?id=".$list_id)->with('article', $article)->with('todoLists',$todoLists);
    }
}

resources/views/todoList/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>To-do list</h1>
    <h3>{{$article->name_list}}</h3>
    <hr>
@stop

@section('content')
<form action="/todoLists" method="post" enctype="multipart/form-data">
    @csrf
    <div class="mb-3">
        <label for="item_todo" class="form-label">Add new to-do</label>
        <input id="list_id" type="text" name="list_id" value="{{$article->id}}" hidden>
        <input id="item_todo" type="text" name="item_todo" class="form-control" placeholder="Name" tabindex="1">
    </div>
    <button type="submit" id="sub" class="btn btn-primary">Submit</button>
</form>
<table width="100%;" border="0" cellspacing="0" cellpadding="0" class="mt-4">
    <tbody>
        @foreach ($todoLists as $todoList)
            <tr style="cursor:pointer;">
                <td style="width:4%; clear:both; @if($todoList->status == 1) background-color:orange; @endif">
                <p class="check"><label class="switch">
                        <input data-id={{$todoList->id}} class="changeStatus" type="checkbox"
                        data-onstyle="success" data-offstyle="danger" data-toggle="toggle"
                        data-on="Active" data-off="InActive" {{$todoList->status ? 'checked' : ''}} id="changeStatus" value="{{$todoList->id}}">
                        <span class="slider round"></span>
                    </label>
                </p>    
                </td>
                <td style="width:31%;clear:both; @if($todoList->status == 1) background-color:orange; @endif">{{$todoList->name_item}}</td>
                <td id="resp{{$todoList->id}}" style="width:20%; @if($todoList->status == 1) background-color:orange; @endif">
                    <br>
                    @if($todoList->status == 1)
                        <span class="badge badge-danger btnStatus">Completed</span>
                    @else
                        <span class="badge badge-success btnStatus">Item left</span>
                    @endif
                </td>
                <td style="width:10%;clear:both; @if($todoList->status == 1) background-color:orange; @endif">
                    <form action="{{ route('todoLists.destroy', $todoList->id) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <p class="btnDelete">
                            <button type="submit" class="btn btn-sm btn-danger" hidden id="btnDelete{{$todoList->id}}">Delete</button>
                            <button id="btnDel" type="button" onclick="del({{$todoList->id}})" data-toggle="modal" data-target="#modal-delete-med-{{$todoList->id}}" title="Delete to-do list" class="btn btn-sm btn-outline-danger mb-2"><i class="fas fa-times"></i></button>
                        </p>
                    </form>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>
@endsection

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
    <style type="text/css">
        #btnDel {
            background-color: #white;
            border-radius: 6px;
            border: none;
            color: #danger;
            cursor: pointer;
            font-size: 15px;
            padding: 4px 10px;
            text-align: center;
            text-transform: uppercase;
            width: auto;
        }
        .btnDelete{
            position: relative;
            top:13px;
        }
        .button:hover {
            background-color: #FB7E29;
            color: #fff;
        }
        .btnStatus {
        text-align: center;
        position: relative;
        top:-12px;
        }
        .check {
        text-align: center;
        position: relative;
        top:13px;
        }
    </style>
    {{-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet"> --}}
@endsection

@section('js')
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="jquery-3.5.1.min.js"></script> --}}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript">

   

    var page = $(location).attr('href');
    function RefreshTable() {
        setTimeout(5000);
        location.reload();
    }

    $(".changeStatus").click(function() {
        changeStatusList($(this).val());
    });
    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
    function changeStatusList(item_id){
                    $.ajax({
                            headers: {
                                'X-CSRF-TOKEN': CSRF_TOKEN
                            },
                            url: "{{ url('/todoLists/update/') }}" + '/' + item_id,
                            type: 'post',
                            dataType: 'json',
                            data: {
                            },
                            success: function(result) {
                                console.log(result);
                                    RefreshTable();
                            },
                            error: function(status) {
                                console.log(status);
                            }

                        });
            }

    function del(id){
         const swalWithBootstrapButtons = Swal.mixin({
              customClass: {
                confirmButton: 'btn btn-outline-success m-3',
                cancelButton: 'btn btn-outline-danger m-3'
              },
              buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
              title: '¿Are you sure you want to delete this?',
              // text: "You won't be able to revert this!",
              icon: 'question',
              showCancelButton: true,
              confirmButtonText: 'Yes',
              cancelButtonText: 'Cancel',
              reverseButtons: true,
              // width: '850px'
            })
            .then((result) => {
              if (result.isConfirmed){
                $('#btnDelete'+id).click();
              }
            })
        }
        $("#sub").click(function(e) {
            var item_todo = document.getElementById('item_todo').value;
            if (item_todo.trim() == '') {
                $('#item_todo').addClass('is-invalid').focus();
                Swal.fire({
                    icon: 'warning',
                    title: 'The item of the list is required'
                });
                return false;
            } else {
                $('#item_todo').removeClass('is-invalid');
            }
    });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
@stop